
package PtestWS.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Wed Apr 23 15:55:12 CEST 2014
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "methodeResponse", namespace = "http://PtestWS/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "methodeResponse", namespace = "http://PtestWS/")

public class MethodeResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

