
package PtestWS.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Wed Apr 23 15:55:12 CEST 2014
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "methode", namespace = "http://PtestWS/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "methode", namespace = "http://PtestWS/")

public class Methode {


}

